#!/bin/sh
ln -sf /opt/gvds/lib/libcouchbase.so.2.0.65 /opt/gvds/lib/libcouchbase.so.2
ln -sf /opt/gvds/lib/libcouchbase.so.2 /opt/gvds/lib/libcouchbase.so
ln -sf /opt/gvds/lib/libpistache.so.0.0 /opt/gvds/lib/libpistache.so.0
ln -sf /opt/gvds/lib/libpistache.so.0 /opt/gvds/lib/libpistache.so

exit 0
