#!/bin/sh
ln -sf /opt/hvs/lib/libcouchbase.so.2.0.65 /opt/hvs/lib/libcouchbase.so.2
ln -sf /opt/hvs/lib/libcouchbase.so.2 /opt/hvs/lib/libcouchbase.so
ln -sf /opt/hvs/lib/libpistache.so.0.0 /opt/hvs/lib/libpistache.so.0
ln -sf /opt/hvs/lib/libpistache.so.0 /opt/hvs/lib/libpistache.so

exit 0
